name: Build & Release Fabric Mod

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 23

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 构建项目
      - name: Build Fabric Mod
        run: |
          chmod +x ./gradlew
          ./gradlew build

      # 读取 gradle.properties 的 mod_version
      - name: Get mod version
        id: mod_version
        run: |
          VERSION=$(grep ^mod_version gradle.properties | cut -d'=' -f2)
          echo "mod_version=$VERSION" >> $GITHUB_OUTPUT

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: veinmine-all.zip
          path: build/libs/*.jar

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ steps.extract-release-info.outputs.title }}
          body: ${{ steps.extract-release-info.outputs.body }}
          files: |
            build/libs/*.jar
            build/libs/*.json
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}