name: Build & Release Fabric Mod

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 构建项目
      - name: Build Fabric Mod
        run: |
          chmod +x ./gradlew
          ./gradlew build

      # 读取 gradle.properties 的 mod_version
      - name: Get mod version
        id: mod_version
        run: |
          VERSION=$(grep ^mod_version gradle.properties | cut -d'=' -f2)
          echo "mod_version=$VERSION" >> $GITHUB_OUTPUT

      # 上传构建产物到 workflow artifact（v4）
      - name: Upload Mod JAR as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: fabric-mod
          path: build/libs/*.jar

      # 创建或更新 Release（新版 ncipollo/release-action）
      - name: Create Release
        uses: ncipollo/release-action@v2
        with:
          tag: ${{ github.ref_name != '' && github.ref_name || steps.mod_version.outputs.mod_version }}
          name: Fabric Mod ${{ steps.mod_version.outputs.mod_version }}
          artifacts: fabric-mod
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
